### ISSUE TITLE
config_scene: program crashes when deadzone slider is moved, trace below

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#71]
~$ python3 '/home/jd/FightstickDisplay-config_scene/fightstick.py' -d
No theme/layout.ini file found. Falling back to default.
Pressed Button: guide
Traceback (most recent call last):
  File "/home/jd/FightstickDisplay-config_scene/fightstick.py", line 339, in <module>
    pyglet.app.run()
  File "/home/jd/FightstickDisplay-config_scene/pyglet/app/__init__.py", line 107, in run
    event_loop.run(interval)
  File "/home/jd/FightstickDisplay-config_scene/pyglet/app/base.py", line 185, in run
    platform_event_loop.step(timeout)
  File "/home/jd/FightstickDisplay-config_scene/pyglet/app/xlib.py", line 120, in step
    device.select()
  File "/home/jd/FightstickDisplay-config_scene/pyglet/canvas/xlib.py", line 202, in select
    dispatch(e)
  File "/home/jd/FightstickDisplay-config_scene/pyglet/window/xlib/__init__.py", line 973, in dispatch_platform_event_view
    event_handler(e)
  File "/home/jd/FightstickDisplay-config_scene/pyglet/window/xlib/__init__.py", line 1465, in _event_button
    self.dispatch_event('on_mouse_press', x, y, button, modifiers)
  File "/home/jd/FightstickDisplay-config_scene/pyglet/window/__init__.py", line 1329, in dispatch_event
    super().dispatch_event(*args)
  File "/home/jd/FightstickDisplay-config_scene/pyglet/event.py", line 415, in dispatch_event
    if handler(*args):
  File "/home/jd/FightstickDisplay-config_scene/pyglet/gui/widgets.py", line 374, in on_mouse_press
    self._update_knob(x)
  File "/home/jd/FightstickDisplay-config_scene/pyglet/gui/widgets.py", line 367, in _update_knob
    self.dispatch_event('on_change', self._value)
  File "/home/jd/FightstickDisplay-config_scene/pyglet/event.py", line 415, in dispatch_event
    if handler(*args):
  File "/home/jd/FightstickDisplay-config_scene/fightstick.py", line 155, in _stick_slider_handler
    config.set('deadzones', 'stick', str(scaled_value))
  File "/usr/lib/python3.6/configparser.py", line 1193, in set
    super().set(section, option, value)
  File "/usr/lib/python3.6/configparser.py", line 901, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'deadzones'

**Comment by benmoran56** [comment]
This should be fixed now also, by my recent commit. Two parts of the same problem.

**Comment by calexil** [comment]
b82bf22
