### ISSUE TITLE
config_scene: app crashes when launched from fightstick.sh script, trace below

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#72]
'/home/jd/FightstickDisplay-config_scene/fightstick.sh' 
~$ Added additional controller mappings from 'gamecontrollerdb.txt'
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'layout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fightstick.py", line 329, in <module>
    load_configuration()
  File "fightstick.py", line 80, in load_configuration
    for key, value in config.items('layout'):
  File "/usr/lib/python3.6/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'layout'

**Comment by calexil** [comment]
b82bf22
