### ISSUE TITLE
hitbox version crashing

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#76]
python3 '/home/jd/Desktop/FightstickDisplay-config_scene/fightstick_hb.py' 
No theme/layouthb.ini file found. Falling back to default.
Traceback (most recent call last):
  File "/home/jd/Desktop/FightstickDisplay-config_scene/pyglet/__init__.py", line 332, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'get_game_controllers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jd/Desktop/FightstickDisplay-config_scene/fightstick_hb.py", line 243, in <module>
    set_scene()
  File "/home/jd/Desktop/FightstickDisplay-config_scene/fightstick_hb.py", line 231, in set_scene
    controllers = pyglet.input.get_game_controllers()
  File "/home/jd/Desktop/FightstickDisplay-config_scene/pyglet/__init__.py", line 342, in __getattr__
    return getattr(module, name)
AttributeError: module 'pyglet.input' has no attribute 'get_game_controllers'

**Comment by calexil** [comment]
@benmoran56 merged two issues, this is now the primary one.

terminal output:

:~/FightstickDisplay$ python3 fightstick_hb.py -d
Failed to parse 'gamecontrollerdb.txt'. Please open an issue on GitHub.
Traceback (most recent call last):
  File "fightstick_hb.py", line 242, in <module>
    load_configuration()
  File "fightstick_hb.py", line 93, in load_configuration
    x, y = value.split(', ')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by calexil** [comment]
I believe the issue may be on line 113

**Comment by calexil** [comment]
https://github.com/calexil/FightstickDisplay/commit/1df4c891dcded42438568d635b9cc1f85b689731
